#!/usr/bin/env bash

# Publish APK

set -e

if [ ! -f AndroidManifest.xml ]; then
	echo "Error: this command must be run from the project root directory."
	exit 1
fi

PROJECT=${PWD##*/}

KEYSTORE=$PROJECT.keystore

if [ ! -f "$KEYSTORE" ]; then
	echo "Error: keystore not found."
	exit 1
fi

PACKAGE=${PWD##*/}.apk

rm -f "$PACKAGE"

ANDROID_JAR=$ANDROID_HOME/platforms/$ANDROID_PLATFORM/android.jar

d8 --release --lib "$ANDROID_JAR" $(find bin -type f -name '*.class')

aapt package -f \
	-I "$ANDROID_JAR" \
	-M AndroidManifest.xml \
	-S res \
	-F "$PACKAGE.unaligned"
  
aapt add -f "$PACKAGE.unaligned" classes.dex

jarsigner \
	-keystore "$KEYSTORE" \
	-storepass android \
	-keypass android \
	"$PACKAGE.unaligned" "$PROJECT"

zipalign 4 "$PACKAGE.unaligned" "$PACKAGE"

rm classes.dex
rm "$PACKAGE.unaligned"

# End

